### PR TITLE
feat(svg): update SVG icons to align with Cosmic design

### PR DESCRIPTION
**Pull request by KodeBarista**

### CODE REVIEW

**Comment by Fingel** [comment]
These SVGs look much better! Thank you. The only problem is they are hardcoded to #000, so they aren't visible with dark themes:
image

**Comment by iamkartiknayak** [comment]
Should I make change it  to `currentColor`?

I couldn't get the styles to load while running in UV so couldn't test out the design completely

**Comment by Fingel** [comment]
> Should I make change it to `currentColor`?
> 
> I couldn't get the styles to load while running in UV so couldn't test out the design completely

I believe so yes. I realize I forgot an install selection. Can you run `npm install` in the project root? That should download the static assets.

**Comment by iamkartiknayak** [comment]
> I believe so yes. I realize I forgot an install instruction. Can you run `npm install` in the project root? That should download the static assets.

I did install the packages manually when npm init didn't work. Still for some reason it's not loading styles. Getting 404 for few 

**Logs:**
```sh
 uv run manage.py migrate && uv run manage.py runserver
warning: `VIRTUAL_ENV=/home/kartik/Downloads/cosmic_themes_venv` does not match the project environment path `.venv` and will be ignored
Operations to perform:
  Apply all migrations: accounts, admin, auth, contenttypes, sessions, themes
Running migrations:
  No migrations to apply.
warning: `VIRTUAL_ENV=/home/kartik/Downloads/cosmic_themes_venv` does not match the project environment path `.venv` and will be ignored
Performing system checks...

System check identified no issues (0 silenced).
October 08, 2024 - 05:55:38
Django version 5.1.1, using settings 'cosmic_themes.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

[08/Oct/2024 05:55:46] "GET / HTTP/1.1" 200 6149
[08/Oct/2024 05:55:46] "GET /static/pico/pico.slate.min.css HTTP/1.1" 404 179
[08/Oct/2024 05:55:46] "GET /static/htmx/htmx.min.js HTTP/1.1" 404 179
[08/Oct/2024 05:55:46] "GET /static/css/main.css HTTP/1.1" 404 179
[08/Oct/2024 05:55:46] "GET /static/img/logo-small.webp HTTP/1.1" 404 179
[08/Oct/2024 05:55:46] "GET /static/alpine/cdn.min.js HTTP/1.1" 404 179
```

**Screenshot:**
image

**Comment by iamkartiknayak** [comment]
I have updated color from `#000` to `currentColor`. Let me know if it works. Kept the height and width intact with original (16x16)

**Comment by Fingel** [comment]
I see the problem. `cosmic_themes/settings.py` has `DEBUG=False` and I have it overwritten to `True` locally using `local_settings.py`. If you change it to `DEBUG=True` in `settings.py` I bet those static requests will work. I'll fix this in a different commit.

In any case, this looks great. Thank you. currentColor working as expected.

**Comment by Fingel** [comment]
Deployed 😁

**Comment by iamkartiknayak** [comment]
> I see the problem. `cosmic_themes/settings.py` has `DEBUG=False` and I have it overwritten to `True` locally using `local_settings.py`. If you change it to `DEBUG=True` in `settings.py` I bet those static requests will work.

Styles are loaded but the themes are not. Am I still missing something here?

image

**Comment by Fingel** [comment]
> Styles are loaded but the themes are not. Am I still missing something here?
No, the repo just doesn't come with any themes pre-loaded for the database. Another thing to add to the list. Some fixtures.

**Pull request merged**
